In [1]:
import requests
import csv
import pandas as pd

response = requests.get("https://gorest.co.in/public/v2/posts")
result = response.json()
result

[{'id': 56992,
  'user_id': 4040734,
  'title': 'Defetiscor eius labore utrum deporto.',
  'body': 'Aperio uredo vesper. Supplanto suasoria adiuvo. Vulgus stella demulceo. Consequatur chirographum vomica. Eos consequatur cilicium. Ipsa cedo vallum. Tenax repellat aestivus. Sint accipio viscus. Vado aggero stillicidium. Coepi claustrum conforto. Vetus curtus accusantium. Capto ipsam pax. Aperio consuasor vero. Aut tredecim terror.'},
 {'id': 56979,
  'user_id': 4040719,
  'title': 'Summa abduco quae blanditiis deorsum.',
  'body': 'Sonitus arca coniecto. Aestivus vae suppono. Vel id voluptatem. Subito bis clam. Administratio denego usitas. Ter cubicularis adulatio. Vomica ascit degenero. Tenax absque ager. Verbera vaco termes. Porro allatus depono. Audacia volo cupiditate. Conservo textor crinis. Nemo acies texo. Coniuratio conicio ulciscor. Tot fugit aegre. Demulceo circumvenio claustrum. Curvus ut comptus. Ut crustulum libero.'},
 {'id': 56978,
  'user_id': 4040713,
  'title': 'Rerum omnis sursum damno terror.',
  'body': 'Denego aptus arma. Placeat decet subvenio. Tabernus unde officia. Abundans amplus vulnero. Aegre error anser. Quod vaco thymum. Comptus triginta agnitio. Quia versus tenus. Est cito ut. Pecus clamo venustas. Peior deficio tripudio. Textus clamo stultus. Caelestis nihil demergo.'},
 {'id': 56973,
  'user_id': 4040709,
  'title': 'Universe officiis qui ceno custodia convoco aeneus repellendus sub.',
  'body': 'Spiculum vox cavus. Arbitro arceo canis. Super virgo demonstro. Curriculum blanditiis conventus. Cura iure magnam. Deprimo terminatio nihil. Quia velociter sit. Coniecto summopere baiulus. Conatus condico artificiose. Cresco velut votum.'},
 {'id': 56969,
  'user_id': 4040706,
  'title': 'Porro vinculum vulgaris custodia ut crapula beatae adversus ademptio.',
  'body': 'Surculus viduo aduro. Ab qui umquam. Tenetur assentator summa. Sub sint et. Tribuo color conturbo. Umerus spoliatio cruentus. Tondeo armarium alias. Terebro voluptatem substantia. Cinis cribro decerno. Necessitatibus ultra animus. Triginta quo et. Eligendi adduco defendo. Chirographum calcar alveus. Eligendi conforto tum. Viriliter eos curia. Comburo universe vix. Pectus concido cupressus.'},
 {'id': 56965,
  'user_id': 4040702,
  'title': 'Condico cunctatio illo vitiosus cupio ut sit.',
  'body': 'Tondeo admoneo theologus. Demitto vilicus ocer. Corroboro adnuo consequatur. Statim curatio vilitas. Deleniti sophismata talio. Timidus virgo angulus. Umerus comedo cernuus. Cupiditas atque subito. Theologus voluptatem copia. Congregatio thesaurus auctor. Surgo sperno dolorem. Cunae recusandae deorsum.'},
 {'id': 56957,
  'user_id': 4040694,
  'title': 'Caterva colo libero talis adnuo.',
  'body': 'Arma aperte decerno. Quas termes dolorem. Volubilis templum comminor. Debilito temperantia sum. Accendo admitto pecus. Benigne advoco alii. Antiquus consectetur cohors. Super debilito acquiro. Vesco laboriosam alias. Viscus tersus tutis. Et vox tristis. Veniam vesper viscus. Artificiose defetiscor est. Agnitio excepturi adhuc. Acervus decerno comprehendo. Trucido civitas coma. Commemoro pecco summa. Summa spes animus.'},
 {'id': 56954,
  'user_id': 4040692,
  'title': 'Derelinquo accommodo attonbitus aqua speciosus.',
  'body': 'Patruus pax comburo. Nesciunt decerno degenero. Vel calco vacuus. Rerum dedico surgo. Statim decumbo confugo. Quisquam tenus delectus. Nostrum talus adipisci. Illo tres tonsor. Arguo cumque titulus. Adnuo arceo spectaculum. Quidem absque timidus. Debilito adfectus autus. Autem facilis est. Quo caries careo. Eum suppellex itaque. Cometes paens enim. Ara sumo non. Verumtamen cura demens. Aut voluptatem arca.'},
 {'id': 56953,
  'user_id': 4040692,
  'title': 'Autem cultura baiulus tonsor ancilla tremo.',
  'body': 'Tamen creptio ulterius. Pecus spes tamdiu. Calcar cruentus error. Auctus tubineus adduco. Denuncio decipio comitatus. Admitto celer degero. Fugit facilis defero. Torqueo asper tamen. Argentum deprecator theca. Ait celebrer ab. Doloremque arma dolore. Animi ut aveho. Voluptatem speciosus aut.'},
 {'id': 56952,
  'user_id': 4040691,
  'title': 'Ustulo armo somnus credo fuga eaque.',
  'body': 'Conicio conqueror tabernus. Allatus synagoga suscipit. Denego solvo basium. Auris vereor ut. Porro odit non. Cubitum universe deleniti. Vorax voluptatem aliquid. Tenus consequatur cognomen. Comedo et catena. Adduco carcer victoria. Corona adulatio provident. Approbo aperte arceo. Tres curvus ante. Totidem tantillus substantia.'}]

In [2]:
result[0]

{'id': 56992,
 'user_id': 4040734,
 'title': 'Defetiscor eius labore utrum deporto.',
 'body': 'Aperio uredo vesper. Supplanto suasoria adiuvo. Vulgus stella demulceo. Consequatur chirographum vomica. Eos consequatur cilicium. Ipsa cedo vallum. Tenax repellat aestivus. Sint accipio viscus. Vado aggero stillicidium. Coepi claustrum conforto. Vetus curtus accusantium. Capto ipsam pax. Aperio consuasor vero. Aut tredecim terror.'}

In [3]:
with open("employees.csv",'w', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=['id', 'user_id', 'title', 'body'])
    writer.writeheader()
    for employees in result:
        i_d = employees['id']
        user_id = employees['user_id']
        title = employees['title']
        body = employees['body']
        writer.writerow(employees)
df = pd.read_csv('employees.csv')
df

,id,user_id,title,body
0,56992,4040734,Defetiscor eius labore utrum deporto.,Aperio uredo vesper. Supplanto suasoria adiuvo...
1,56979,4040719,Summa abduco quae blanditiis deorsum.,Sonitus arca coniecto. Aestivus vae suppono. V...
2,56978,4040713,Rerum omnis sursum damno terror.,Denego aptus arma. Placeat decet subvenio. Tab...
3,56973,4040709,Universe officiis qui ceno custodia convoco ae...,Spiculum vox cavus. Arbitro arceo canis. Super...
4,56969,4040706,Porro vinculum vulgaris custodia ut crapula be...,Surculus viduo aduro. Ab qui umquam. Tenetur a...
5,56965,4040702,Condico cunctatio illo vitiosus cupio ut sit.,Tondeo admoneo theologus. Demitto vilicus ocer...
6,56957,4040694,Caterva colo libero talis adnuo.,Arma aperte decerno. Quas termes dolorem. Volu...
7,56954,4040692,Derelinquo accommodo attonbitus aqua speciosus.,Patruus pax comburo. Nesciunt decerno degenero...
8,56953,4040692,Autem cultura baiulus tonsor ancilla tremo.,Tamen creptio ulterius. Pecus spes tamdiu. Cal...
9,56952,4040691,Ustulo armo somnus credo fuga eaque.,Conicio conqueror tabernus. Allatus synagoga s...

In [4]:
result_users = requests.get("https://gorest.co.in/public/v2/users")
result = result_users.json()
result[0]

{'id': 4040694,
 'name': 'Bhasvan Kapoor',
 'email': 'bhasvan_kapoor@adams.test',
 'gender': 'female',
 'status': 'inactive'}

In [5]:
with open("status.csv",'w', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=['id', 'name', 'email', 'gender','status'])
    writer.writeheader()
    for employees in result:
        i_d = employees['id']
        name = employees['name']
        email = employees['email']
        gender = employees['gender']
        status = employees['status']
        writer.writerow(employees)
df = pd.read_csv('status.csv')
df

,id,name,email,gender,status
0,4040694,Bhasvan Kapoor,bhasvan_kapoor@adams.test,female,inactive
1,4040692,Fr. Deenabandhu Sinha,deenabandhu_sinha_fr@oreilly.test,female,active
2,4040691,Chaturbhuj Reddy,chaturbhuj_reddy@quitzon-reichel.test,male,active
3,4040690,Saraswati Dhawan,saraswati_dhawan@larkin.example,male,active
4,4040689,Rep. Aayushman Bhat,rep_aayushman_bhat@tremblay.test,female,inactive
5,4040686,Bhima Chaturvedi,chaturvedi_bhima@barrows.example,male,inactive
6,4040685,Tushar Ahluwalia,ahluwalia_tushar@franecki.test,male,active
7,4040684,Dhanesh Arora PhD,dhanesh_phd_arora@maggio.test,male,active
8,4040683,Dharani Kocchar,kocchar_dharani@heller-torp.test,male,active
9,4040682,Uma Bhattacharya,bhattacharya_uma@cassin-yost.example,male,inactive